apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: devops-tools
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.jenkins.ingress.host }}
      http:
        paths:
          - path: {{ .Values.jenkins.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.jenkins.ingress.serviceName }}
                port:
                  number: {{ .Values.jenkins.ingress.servicePort }}